# Generated by Django 3.2.13 on 2022-05-14 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa domeny')),
                ('urlAddress', models.URLField(max_length=1000, verbose_name='Adres URL')),
                ('intervals', models.CharField(choices=[('01', '1 minute'), ('05', '5 minutes'), ('15', '15 minutes'), ('30', '30 minutes'), ('60', '60 minutes')], default='01', max_length=5, verbose_name='Interwały czasowe')),
                ('isWorking', models.BooleanField(blank=True, default=True, verbose_name='Czy działa')),
            ],
            options={
                'ordering': ('intervals', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnCode', models.CharField(max_length=3, verbose_name='Kod błędu')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Data zdażenia')),
                ('websiteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='MonitoringManager.websites')),
            ],
            options={
                'ordering': ('websiteId', 'time'),
            },
        ),
    ]
