# Generated by Django 3.2.13 on 2022-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='md5',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
