# Generated by Django 3.2.13 on 2022-05-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoringManager', '0005_auto_20220514_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('websiteId', '-time')},
        ),
    ]
